### ISSUE TITLE
heartbeat (recalculating of times after midnight) not working for sun.js...

### ISSUE THREAD

**Issue by codepoet4** [dpjanes/iotdb-timers#3]
From the code, you have a typo of sorts in sun.js:

```
    // heartbeat
    // see https://github.com/dpjanes/iotdb-timers/issues/1
    // for possible improvements
    self._schedule({
        id: "recalcuate-heartbeat",
        hour: 0,
        day_repeat: 1
    })

    self.on("recalculate", self._recalculate);
```

You can See that the 'id' for the heartbeat is 'recalcuate-heartbeat', yet the event in the .on() is 'recalculate'.  Not sure why you have the '-heartbeat' at the end, and you also missed the second 'l' (ell) in recalculate.  (recalcu l ate, not recalcu ate)

**Comment by dpjanes** [comment]
Ough. I just pushed a fix.

**Comment by codepoet4** [comment]
Looks good.  I've got in 'in production' and I'll know after midnight if it worked...

**Comment by codepoet4** [comment]
In pushing this fix, you also pushed a change to timer.js where you changed logger.error to logger.warn.... However, without bunyan, your make_logger function in helpers.js is missing the 'warn' keyword...

`exports.make_logger = function(d) {
    if (bunyan) {
        return bunyan.createLogger({
            name: 'iotdb-timer',
            module: 'timer',
        });
    } else {
        var l = function() {
            console.log("--");
            for (var ai in arguments) {
                console.log(JSON.stringify(arguments[ai], null, 2).replace(/^/gm, '  '));
            }
        };

```
    return {
        debug: l,
        trace: l,
        info: l,
        error: l,
    };
}`
```

**Comment by dpjanes** [comment]
Arggg. I've started using logger.warn more recently. Updated.

**Comment by codepoet4** [comment]
Hmmm...  Interestingly, the dates didn't recalculate.  I forced the emit at 5am this morning, and they did update, so I'm not sure what happened at midnight.  I'll also add a logger so I can look back to see what is happening or not happening.  I'll let you know what I find.

**Comment by dpjanes** [comment]
Thank you. I wish there was some sort of straight forward way I could write test cases for this, but it's so difficult with time-based stuff.

**Comment by dpjanes** [comment]
Try adding a logging message to

Sun.prototype._recalculate

And see if it's triggered at midnight

**Comment by codepoet4** [comment]
That was the plan ;)

**Comment by codepoet4** [comment]
Wow, this is fun...  I put the clock to kathmandu, then somewhere in pakistan, before finding that the issue is in Suncalc:

https://github.com/mourner/suncalc/issues/11

OK, now I see what's going on here — SunCalc calculates all the times after it gets the time of the nearest solar transit. But solar transit isn't strictly 12am — e.g. if it's 12:44am, then 0:43am as input will result in dates of the previous day since its transit is closer.

The fix was to call suncalc with:

replace your gettimes calls with a **suncalc.getTimes(new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12, 0, 0, 0, 0), lat, long)**

**Comment by dpjanes** [comment]
Great find. Does this look right - basically you're calculating from noon
that day?

```
var dt_now = new Date();

var dt_noon = new Date(dt_now.getFullYear(), dt_now.getMonth(),
```

dt_now.getDate(), 12, 0, 0, 0, 0);

```
var td = suncalc.getTimes(dt_noon, self.paramd.latitude, self
```

.paramd.longitude);

**Comment by codepoet4** [comment]
That is how I interpret it, yes. :)

**Comment by dpjanes** [comment]
Pushed!

**Comment by codepoet4** [comment]
Well, as hard as I've been trying to close this issue...I do believe this is the fix.  Unfortunately, it now seems to crash at midnight (happened the 3 times I've tried to test this fix).  I don't know if the crash is related to this fix (I think it is, however).   One thing to note - because I was running node with 'forever' last night, it restarted right away and did calculate the proper sunset time for the new day...   So, if it didn't crash, I believe this fixes the problem :)

Regarding the crash...  I'm heading away on vacation, so I should have lots of time to test this on the weekend ;)  (Unless you can look at the code and figure it out)

**Comment by codepoet4** [comment]
```
    // heartbeat
    // see https://github.com/dpjanes/iotdb-timers/issues/1
    // for possible improvements
    self._schedule({
        id: HEARTBEAT_ID,
        hour: 0,
        day_repeat: 1
    })
```

Just glancing at the code... should there not be a ';' at the end of the above statement?  (I'm new to javascript/nodejs, so I apologize if this is a stupid question).

edit: Ignore this... I see it is optional in javascript in a lot of places...

**Comment by dpjanes** [comment]
Semicolons are optional in JS, though I generally add them. I'm going to
run up a Raspberry Pi and leave it running with this and see what we get.

**Comment by dpjanes** [comment]
Definitely see the crash and it's a mystery. Now trying to solve it.

**Comment by codepoet4** [comment]
I'm slowly adding more debug to figure this out.  Looks like it gets to the top of hour schedule for the heartbeat and then it gets into _schedule then to _execute, the right back to _schedule, _execute, etc.., etc..., etc....    Eventually crashing from that infinite loop.  

I can get it to crash almost every hour... By changing the heartbeat hour:0 to the next hour.

**Comment by dpjanes** [comment]
Interesting, I'm at same point as you. I've made a ton of changes here and
did the same thing - I did minute - but am not seeing crashes yet.

I'm not sure if they're checkin in, but I've added test cases, did jshint
code scrub, added missing semicolons.

**Comment by dpjanes** [comment]
Maybe timing related? _schedule -> _reschedule … and it gets right now and
executes again and again?

Do you see a whole pile of execute messages (i.e. event being pushed?)

**Comment by codepoet4** [comment]
Sort of...  It emits the heartbeat, then does the recalc, that calls the _schedule for the new sunset (in my case), that calls the _scheduler that calls the SAME event - and the sequence continues.   It's like the _scrub isn't quite deleting the previous event properly...  

I find your _scrub function a bit confusing - it does delete 4 keys from the heartbeat event, according to my log, but it still seems to be intact when it comes back again on the next loop.  

It does have this looping problem for most top of hours, but not all... A few times it behaved as expected.

**Comment by dpjanes** [comment]
I got through the whole night with a minute reschedule without a crash,
though I'm not sure why.

I've added documentation to _scrub: basically "self._dd" holds private
information that shouldn't shared, so it deletes it (from a clone). If I
was writing this today, I would take a different approach but my Node
programming has gotten a little better.

I've added this to recalculate

```
// to avoid the same sunrise and sunset being rescheduled over and over

setTimeout(function() {

    self._schedule(self.when);

}, 1000);
```

**Comment by dpjanes** [comment]
I've just pushed all my changes to github (but not npm), if you'll like to
see them.

**Comment by codepoet4** [comment]
That seems to have done the trick.  I added only the 1 second delay to the recalculate routine, and it's not crashing anymore.  I'll put it into my production environment and see what happens at midnight ;)

**Comment by dpjanes** [comment]
Awesome. Note that I did it slightly differently in what I pushed afterward
- I delay the whole recalculation for 1 second.

I'm running it too right now.

**Comment by dpjanes** [comment]
I've done a dist to npm. No crashes on my side.

**Comment by codepoet4** [comment]
Same here - all is good.
